version: "3"

services:
  nodegraph-generator:
    build: .
    ports:
      - "8080:8080"
    environment:
      - VM_HOST=localhost:8427
    network_mode: "host"
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_PLUGINS_PREINSTALL: yesoreyeram-infinity-datasource
      GF_PATHS_PROVISIONING: /provisioning
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_ANONYMOUS_HIDE_VERSION: "false"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /provisioning/service-graph.json
    volumes:
      - ./provisioning:/provisioning
    network_mode: "host"
    restart: unless-stopped
